### ISSUE TITLE
Error -54: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel). Round 1, part 0

### ISSUE THREAD

**Issue by johndpope** [XDNA-Core/sgminer-hex#2]
[15:33:22] Error -54: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel). Round 1, part 0
[15:33:22] GPU 0 failure, disabling!

am seeing this on two different operating systems.

Can you offer some insight into your current setup? or recommended system ram. 
Can this run with just 4 gigs of RAM?

```shell

[P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
GPU 0:                | OFF   / 0.000h/s | R:  0.0% HW:0 WU:0.000/m I:22

I hit G -> Enable
but no joy

(5s):0.000 (avg):0.000h/s | A:0  R:0  HW:0  WU:0.000/m
ST: 2  SS: 0  NB: 3  LW: 115  GF: 0  RF: 0
Connected to stratum.gos.cx (stratum) diff 8.000 as user XWn8BDU4QXHQji6insi33CYeTEr5N4sn34
Block: 59967ad1...  Diff:1.5K  Started: [15:35:59]  Best share: 0
--------------------------------------------------------------------------------
[P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
GPU 0:                |  0.000/ 0.000h/s | R:  0.0% HW:0 WU:0.000/m I:22
--------------------------------------------------------------------------------
GPU 0: 0.0 / 0.0 Kh/s | A:0  R:0  HW:0  U:0.00/m  I:22  xI:0  rI:0
Last initialised: [2018-08-14 15:33:20]
Thread 0: 0.0 Kh/s Disabled ALIVE

[E]nable  [D]isable  [R]estart GPU
[I]ntensity  E[x]perimental intensity  R[a]w Intensity
Or press any other key to continue
GPU 0: 0.0 / 0.0 Kh/s | A:0  R:0  HW:0  U:0.00/m  I:22  xI:0  rI:0
Last initialised: [2018-08-14 15:33:20]
Thread 0: 0.0 Kh/s Enabled ALIVE

[E]nable  [D]isable  [R]estart GPU
[I]ntensity  E[x]perimental intensity  R[a]w Intensity
Or press any other key to continue
```

**Comment by marikuns** [comment]
try with last commit

**Comment by johndpope** [comment]
is there a way (as a sanity check) to launch miner in a mode where it generates its' own genesis block locally and starts mining with 0 difficulty? or maybe connect to a testnet ?

I'm seeing it connect to pool - but there's no hashing.
--------------------------------------------------------------------------------
(5s):0.000 (avg):0.000h/s | A:0  R:0  HW:0  WU:0.000/m
ST: 2  SS: 0  NB: 8  LW: 222  GF: 0  RF: 0
Connected to stratum.gos.cx (stratum) diff 8.000 as user XWn8BDU4QXHQji6insi33CYeTEr5N4sn34
Block: 2d6ae9e8...  Diff:1.16K  Started: [08:24:37]  Best share: 0
--------------------------------------------------------------------------------
[P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
GPU 0:                | OFF   / 0.000h/s | R:  0.0% HW:0 WU:0.000/m I: 8
GPU 1:                |  0.000/ 0.000h/s | R:  0.0% HW:0 WU:0.000/m I: 8
--------------------------------------------------------------------------------

**Comment by johndpope** [comment]
[ERROR  ] 18/08/17 20:12:20 GPU#0: Unsupported compute capability device. Ignoring
can't seem to get p2 or g2 spot instance to work.
https://gist.github.com/johndpope/ac3ae5f4e033d1ca6c94d3387e4dc309

**Comment by marikuns** [comment]
sometimes there is no work from pool. Simply pool doesnt send it. 

By your second question. Are you sure that AWS EC2 use amd? and why you select 16 work size?

**Comment by johndpope** [comment]
OMG @marikuns - thanks - I skipped that dependency. 
Though, I tried to use z-enemy to no avail too. 
Eager to get hands on some xdna. 

Need to add some code to do cpu detection and throw error. I'll add as an enhancement.
